apiVersion: apps/v1
kind: Deployment
metadata:
    name: texttech-deployment
    labels:
        app: texttech
spec:
    replicas: 1
    selector:
        matchLabels:
            app: texttech
    template:
        metadata:
            labels:
                app: texttech
        spec:
            containers:
                - name: texttech
                  image: drashti114/texttech-app:latest
                  ports:
                      - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
    name: texttech-service
spec:
    selector:
        app: texttech
    ports:
        - protocol: TCP
          port: 80
          targetPort: 3000
    type: NodePort
