name: Comment on New Issue

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest

    permissions:
      issues: write  # Needed to comment on issues

    steps:
      - name: Comment "new issue" on the issue
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Commit message: `new issue`"
            })
