name: Build and Push Docker Image

on:
 pull_request:
    branches:
    - master
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: run command
        run: echo ${GITHUB_REPOSITORY}
      - name: run command
        run: echo ${{github.event.name}}
